# Dev and infra packages renv should track (never sourced)
library(IRkernel)
library(languageserver)
library(vscDebugger)
library(jsonlite)
library(rlang)
library(R6)
library(ggplot2)
library(yaml)
library(rmarkdown)
library(knitr)

# Pipeline and reports (used by _targets.R / tar_quarto(), listed so renv records them)
library(targets)
library(tarchetypes)
library(quarto)
library(visNetwork)
