# The data catalogue (bookkeeping, not analysis): one row per input file under data/.
#
#   metadata/auto_catalogue_data.tsv   generated by scripts/sh/catalogue-data.sh (git-ignored)
#   metadata/catalogue_data.tsv        your reviewed copy (committed)
#
# The generated file starts from your reviewed copy: it keeps your descriptive columns (and any columns
# you added), refreshes the file facts, adds new files and marks vanished ones "missing". Review it,
# then copy it over the reviewed file to accept the changes.

catalogue_auto <- c("file", "original_path", "host", "format", "read", "size", "owner",
                    "modified", "md5", "status", "first_catalogued")
catalogue_manual <- c("kind", "sample", "title", "library_strategy", "library_type", "organism",
                      "tissue", "cell_type", "treatment", "molecule", "layout", "instrument",
                      "source", "description")

#' File format from the name, keeping compression: x.fq.gz -> fastq.gz, x.mtx.gz -> mtx.gz, x.h5 -> h5
file_format <- function(path) {
  name <- tolower(basename(path))
  comp <- regmatches(name, regexpr("\\.(gz|bz2|xz|zst|zip)$", name))
  base <- sub("\\.(gz|bz2|xz|zst|zip)$", "", name)
  ext <- if (grepl("\\.", base)) sub("^.*\\.", "", base) else ""
  aliases <- c(fq = "fastq", fa = "fasta", yml = "yaml")
  if (ext %in% names(aliases)) ext <- aliases[[ext]]
  paste0(ext, if (length(comp) == 1) comp else "")
}

#' Read number from sequencing file names: ..._R1_001.fastq.gz, ...R2.fq.gz, ..._I1_001.fq.gz
read_label <- function(path) {
  m <- regmatches(basename(path), regexpr("(?<=[_.])(R[1-3]|I[12])(?=[_.])", basename(path), perl = TRUE))
  if (length(m) == 1) m else ""
}

human_size <- function(b) {
  if (is.na(b)) "" else format(structure(b, class = "object_size"), units = "auto")
}

read_catalogue <- function(file) {
  cols <- c(catalogue_auto, catalogue_manual)
  tab <- if (file.exists(file)) {
    read.delim(file, colClasses = "character", na.strings = character(), check.names = FALSE)
  } else {
    as.data.frame(setNames(replicate(length(cols), character(), simplify = FALSE), cols))
  }
  for (col in setdiff(cols, names(tab))) tab[[col]] <- rep("", nrow(tab))
  tab
}

#' Scan data/ (following linked folders) and write metadata/auto_catalogue_data.tsv
update_catalogue <- function(data_dir = "data",
                             reviewed = "metadata/catalogue_data.tsv",
                             out = "metadata/auto_catalogue_data.tsv",
                             md5 = TRUE) {
  base <- read_catalogue(reviewed)                  # descriptions and known checksums come from here
  last <- read_catalogue(out)                       # checksums from the previous scan, to avoid rehashing
  files <- setdiff(list.files(data_dir, recursive = TRUE), "README.md")
  now <- format(Sys.time(), "%Y-%m-%d %H:%M")

  known_md5 <- function(f, modified, size) {
    for (tab in list(last, base)) {
      p <- tab[tab$file == f, , drop = FALSE]
      if (nrow(p) == 1 && p$modified == modified && p$size == size && nzchar(p$md5)) return(p$md5)
    }
    NA_character_
  }

  rows <- lapply(files, function(f) {
    real <- normalizePath(file.path(data_dir, f), mustWork = FALSE)
    info <- file.info(real, extra_cols = TRUE)
    prev <- base[base$file == f, , drop = FALSE]
    modified <- format(info$mtime, "%Y-%m-%d %H:%M:%S")
    size <- human_size(info$size)
    checksum <- known_md5(f, modified, size)
    if (is.na(checksum)) checksum <- if (md5) unname(tools::md5sum(real)) else ""
    auto <- list(file = f, original_path = real, host = Sys.info()[["nodename"]],
                 format = file_format(f), read = read_label(f), size = size, owner = info$uname,
                 modified = modified, md5 = checksum, status = "present",
                 first_catalogued = if (nrow(prev) == 1 && nzchar(prev$first_catalogued))
                   prev$first_catalogued else now)
    row <- if (nrow(prev) == 1) prev else base[0, , drop = FALSE][1, , drop = FALSE]
    row[is.na(row)] <- ""
    row[names(auto)] <- auto
    row
  })
  new <- if (length(rows)) do.call(rbind, rows) else base[0, , drop = FALSE]

  gone <- base[!base$file %in% files, , drop = FALSE]
  gone$status <- rep("missing", nrow(gone))
  tab <- rbind(new, gone)
  tab <- tab[order(tab$file), c(catalogue_auto, catalogue_manual,
                                setdiff(names(tab), c(catalogue_auto, catalogue_manual))), drop = FALSE]
  dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)
  write.table(tab, out, sep = "\t", quote = FALSE, row.names = FALSE, na = "")

  # What a review should look at, compared with the reviewed copy
  m <- merge(base[, c("file", "md5")], tab[, c("file", "md5")], by = "file", suffixes = c(".rev", ".now"))
  invisible(list(
    table    = tab,
    added    = setdiff(files, base$file),
    missing  = gone$file,
    changed  = m$file[nzchar(m$md5.rev) & nzchar(m$md5.now) & m$md5.rev != m$md5.now],
    reviewed = file.exists(reviewed)
  ))
}
